name: project_nlp
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.0.0
  - torchvision=0.15.0
  - torchaudio=2.0.0
  - pytorch-cuda=11.8
  - numpy<2.0.0
  - pandas
  - pip
  - pip:
    - pytorch-lightning==1.9.0
    - transformers
    - wandb
    - hydra-core
    - omegaconf
    - rouge-score
    - rouge
    - tqdm
    - pybind11>=2.12


